### ISSUE TITLE
Todo ?

### ISSUE THREAD

**Issue by vegarringdal** [vegarringdal/aurelia-plugin-skeleton-typescript#1]
@shahabganji @HamedFathi 
Maybe we could make some issues on what to do etc

If you have something you want to add then create a issue and assign your self so we dont work on the same
When we feel we got most of whats needed we could call it 1.0.0 and use branches on new features etc

**Comment by HamedFathi** [comment]
@vegarringdal @shahabganji 

I think we can close 1.0.0 although I prefer to have Jest + Puppeteer as E2E too

**Comment by vegarringdal** [comment]
> I think we can close 1.0.0 although I prefer to have Jest + Puppeteer as E2E too

@HamedFathi 
Sounds like a good plan, can u try and add it ?
the more complete we get it the better :-)

**Comment by HamedFathi** [comment]
@vegarringdal 

I added [jest-puppeteer](https://github.com/smooth-code/jest-puppeteer) for E2E testing but I am not sure is it fully working with Aurelia or not but I added a simple test for the page title and it works.

**Comment by vegarringdal** [comment]
@HamedFathi great

maybe we could add some more information to the readme ?

we have a lot of scripts :-)
nice for others to know what they do

    "build": "node ./scripts/build.js"
    "setup": "node ./scripts/setup.js",
    "watch": "node ./scripts/watch.js",
    "eslint": "node ./node_modules/eslint/bin/eslint scripts",
    "eslintFix": "node ./node_modules/eslint/bin/eslint scripts --fix",
    "unit-test": "./node_modules/.bin/jest --config=jest.unit.config.json",
    "unit-test-coverage": "./node_modules/.bin/jest --coverage --config=jest.unit.config.json",
    "unit-test-watch": "./node_modules/.bin/jest --config=jest.unit.config.json --watch",
    "e2e-test": "./node_modules/.bin/jest --config=jest.e2e.config.json"

**Comment by vegarringdal** [comment]
@shahabganji @HamedFathi
do we want to use typescript for scripts too?
we could call it scriptTS and the build from it could be in script folder.
what dobu guys think? Im kinda gotten used to using typescript everywhere :-)

**Comment by shahabganji** [comment]
You guys are so active, I Kinda have no preference, but typescript is more type safe and less error-prone, so might be so perfect a choice.

**Comment by vegarringdal** [comment]
closing this.
@HamedFathi @shahabganji when you guys are happy then release it to v1.0.0 and ask for feedback on discourse.
From the feedback we can decide what to improve/change :-)
